version: "3.8"

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: informica_qdrant
    ports:
      - "${QDRANT_PORT:-6333}:6333"
    volumes:
      - "./${BASE_PATH}/${MODEL_PATH}:/var/lib/qdrant"
    environment:
      - QDRANT__STORAGE__STORAGE_PATH=/var/lib/qdrant
      - QDRANT__LOG_LEVEL=INFO
    command: ["/bin/bash", "-c", "sleep 2 && /qdrant/entrypoint.sh"]
    restart: on-failure
